name: Build and Deploy

on:
  push:
    branches:    
      - blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: blog
        BRANCH: master
        FOLDER: public
        BUILD_SCRIPT: |
          npm install
          npm run build
          echo "theme: jekyll-theme-cayman" > public/_config.yml

